site_name: life-log
site_url: https://wangzh12023.github.io/life-log/
copyright: 'Copyright &copy; Wangzh'
 


theme:
  name: material
  custom_dir: overrides
  logo: assets/avatar.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share




extra_css:
  - stylesheets/special.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 


markdown_extensions:
  - toc:
      permalink: "¶"
  - footnotes
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - blog:
      archive: true
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - statistics:
      page_read_time: true
      page_check_metadata: comments
  - macros
  - rss:
      match_path: 'blog/posts/.*'
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags


# extra:
#   homepage: Home/home2.html